version: '3'

volumes:
  static:
  database:

services:
  MyBlog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: MyBlog
    container_name: MyBlog
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: MyBlog_nginx
    container_name: MyBlog_nginx
    volumes:
      - static:/apps/MyBlog/static
    ports:
      - "80:80"
      - "443:443"